export const pricingPlans = [
  {
    name: "Premium Plan",
    price: "₹99",
    period: "for one month",
    description: "For individual users who want full access.",
    cta: "Upgrade to Premium",
    featuresIntro: "Everything in Free Plan plus:",
    features: [
      "100 credits for one month",
      "Unlimited chats per project",
      "Access to all and latest models",
      "Deploy your website instantly.",
      "No watermark on code/website",
    ],
    payment_type: "one_time",
  },
  {
    name: "Premium Plan Subscription",
    price: "₹99",
    period: "per month",
    description: "For individual users with automatic monthly billing.",
    cta: "Subscribe to Premium",
    featuresIntro: "Everything in Free Plan plus:",
    features: [
      "100 credits every month",
      "Unlimited chats per project",
      "Access to all and latest models",
      "Deploy your website instantly.",
      "No watermark on code/website",
    ],
    payment_type: "subscription",
  },

  {
    name: "Testing Premium Plan",
    price: "₹9",
    period: "for 1 day",
    description: "Short-term premium access for testing and evaluation.",
    cta: "Try Premium",
    featuresIntro: "All Premium features for 1 day:",
    features: [
      "10 credits valid for 1 day",
      "Unlimited chats per project",
      "Access to all and latest models",
      "Deploy your website instantly.",
      "No watermark on code/website",
    ],
    payment_type: "one_time",
    plan_category: "testing",
  },
];
